FROM node:20-alpine

WORKDIR /app

RUN apk add --no-network --no-cache make gcc g++ python3

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --legacy-peer-deps

RUN npx prisma generate

COPY . .

RUN npm run build

RUN mkdir -p uploads

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && node dist/src/main.js"]