    FROM node:20-alpine

    WORKDIR /app

    COPY package*.json ./

    RUN npm ci --legacy-peer-deps

    ARG NEXT_PUBLIC_API_BASE_URL

    ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

    COPY . .

    RUN npm run build

    EXPOSE 5000

    CMD ["npm", "start"]