/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * My Backend by Ghost Raven
 * This API works with several entities: Users,Items and e.t.c. Each User can have multiple Items.
 * OpenAPI spec version: 1.0
 */
import { createInstance } from "../api-instance";
import type { BodyType } from "../api-instance";
export interface PhotoDto {
  id: number;
  url: string;
  filename: string;
}

export interface UserDto {
  id: number;
  email: string;
  name?: string;
  photo: PhotoDto | null;
}

export interface UpdateProfileDto {
  [key: string]: unknown;
}

export interface UpdateUserDto {
  [key: string]: unknown;
}

export interface AccountDto {
  id: number;
  ownerId: number;
  isBlockingEnabled: boolean;
}

export interface PatchAccountDto {
  isBlockingEnabled?: boolean;
}

export type BlockItemDtoType =
  (typeof BlockItemDtoType)[keyof typeof BlockItemDtoType];

export const BlockItemDtoType = {
  KeyWord: "KeyWord",
  Website: "Website",
} as const;

export interface BlockItemDto {
  id: number;
  blockListid: number;
  type: BlockItemDtoType;
  data: string;
  createdAt: string;
}

export interface BlockListDto {
  id: number;
  ownerId: number;
  items: BlockItemDto[];
}

export type AddBlockItemDtoType =
  (typeof AddBlockItemDtoType)[keyof typeof AddBlockItemDtoType];

export const AddBlockItemDtoType = {
  KeyWord: "KeyWord",
  Website: "Website",
} as const;

export interface AddBlockItemDto {
  type: AddBlockItemDtoType;
  data: string;
}

export interface UploadPhotoDto {
  /** Выберите несколько файлов */
  files: string[];
  /** Id предмета */
  itemId: string;
}

export interface CreateContentDto {
  /** Тип небесного тела */
  type: string;
  /** Сабтип небесного тела */
  subtype: string;
  /** Размер в км */
  size: string;
}

export interface PhotoRecordDto {
  url: string;
  filename: string;
  originalName: string;
}

export interface CreateItemDto {
  id: number;
  /** название объекта */
  title: string;
  /** Данные контента (вложенный объект) */
  content: CreateContentDto;
  /** Опубликована ли статья */
  published: boolean;
  /** ID автора статьи */
  authorId: number;
  /** Список данных о загруженных фотографиях */
  photos?: PhotoRecordDto[];
  createdAt?: string;
}

/**
 * @nullable
 */
export type PaginatedItemDtoNextPage = { [key: string]: unknown } | null | null;

export interface PaginatedItemDto {
  data: CreateItemDto[];
  total: number;
  /** @nullable */
  nextPage: PaginatedItemDtoNextPage;
}

export interface UpdateItemDto {
  id?: number;
  /** название объекта */
  title?: string;
  /** Данные контента (вложенный объект) */
  content?: CreateContentDto;
  /** Опубликована ли статья */
  published?: boolean;
  /** ID автора статьи */
  authorId?: number;
  /** Список данных о загруженных фотографиях */
  photos?: PhotoRecordDto[];
  createdAt?: string;
}

export interface SignUpBodyDto {
  email: string;
  name: string;
  password: string;
}

export interface SignInBodyDto {
  email: string;
  password: string;
}

export interface GetSessionInfoDto {
  id: number;
  email: string;
  iat: number;
  exp: number;
}

export interface ChangePasswordDto {
  oldPassword: string;
  newPassword: string;
  confirmNewPassword: string;
}

export type UserControllerUploadAvatarBody = {
  file?: Blob;
};

export type BlockListControllerGetListParams = {
  q?: string;
};

export type ItemControllerFindAllItemsParams = {
  page: number;
  limit: number;
  search: string;
  sort: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить всех пользователей
 */
export const userControllerFindAll = (
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/users`, method: "GET" }, options);
};

export const userControllerGetMe = (
  options?: SecondParameter<typeof createInstance<UserDto>>,
) => {
  return createInstance<UserDto>({ url: `/users/me`, method: "GET" }, options);
};

export const userControllerUpdateProfile = (
  updateProfileDto: BodyType<UpdateProfileDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  const formData = new FormData();

  return createInstance<void>(
    {
      url: `/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};

/**
 * @summary Получить одного пользователя
 */
export const userControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/users/${id}`, method: "GET" }, options);
};

/**
 * @summary Обновить пользователя
 */
export const userControllerUpdate = (
  id: string,
  updateUserDto: BodyType<UpdateUserDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/users/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserDto,
    },
    options,
  );
};

/**
 * @summary Удалить пользователя
 */
export const userControllerRemove = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/users/${id}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary Загрузка аватара пользователя
 */
export const userControllerUploadAvatar = (
  userControllerUploadAvatarBody: BodyType<UserControllerUploadAvatarBody>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  const formData = new FormData();
  if (userControllerUploadAvatarBody.file !== undefined) {
    formData.append(`file`, userControllerUploadAvatarBody.file);
  }

  return createInstance<void>(
    {
      url: `/users/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};

export const accountControllerGetAccount = (
  options?: SecondParameter<typeof createInstance<AccountDto>>,
) => {
  return createInstance<AccountDto>(
    { url: `/account`, method: "GET" },
    options,
  );
};

export const accountControllerPatchAccount = (
  patchAccountDto: BodyType<PatchAccountDto>,
  options?: SecondParameter<typeof createInstance<PatchAccountDto>>,
) => {
  return createInstance<PatchAccountDto>(
    {
      url: `/account`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchAccountDto,
    },
    options,
  );
};

export const blockListControllerGetList = (
  params?: BlockListControllerGetListParams,
  options?: SecondParameter<typeof createInstance<BlockListDto>>,
) => {
  return createInstance<BlockListDto>(
    { url: `/block-list`, method: "GET", params },
    options,
  );
};

export const blockListControllerAddBlockItem = (
  addBlockItemDto: BodyType<AddBlockItemDto>,
  options?: SecondParameter<typeof createInstance<BlockItemDto>>,
) => {
  return createInstance<BlockItemDto>(
    {
      url: `/block-list/item`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addBlockItemDto,
    },
    options,
  );
};

export const blockListControllerRemoveBlockItem = (
  id: number,
  options?: SecondParameter<typeof createInstance<BlockItemDto>>,
) => {
  return createInstance<BlockItemDto>(
    { url: `/block-list/item/${id}`, method: "DELETE" },
    options,
  );
};

export const photoControllerUploadPhoto = (
  uploadPhotoDto: BodyType<UploadPhotoDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  const formData = new FormData();
  uploadPhotoDto.files.forEach((value) => formData.append(`files`, value));
  formData.append(`itemId`, uploadPhotoDto.itemId);

  return createInstance<void>(
    {
      url: `/photos/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};

/**
 * @summary Удалить фотографию по ID
 */
export const photoControllerRemovePhoto = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/photos/${id}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary Создать все новые айтемы
 */
export const itemControllerCreateItem = (
  createItemDto: BodyType<CreateItemDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/Items`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createItemDto,
    },
    options,
  );
};

/**
 * @summary Получить все айтемы
 */
export const itemControllerFindAllItems = (
  params: ItemControllerFindAllItemsParams,
  options?: SecondParameter<typeof createInstance<PaginatedItemDto>>,
) => {
  return createInstance<PaginatedItemDto>(
    { url: `/Items`, method: "GET", params },
    options,
  );
};

/**
 * @summary Получить один айтем
 */
export const itemControllerFindOneItem = (
  id: string,
  options?: SecondParameter<typeof createInstance<CreateItemDto>>,
) => {
  return createInstance<CreateItemDto>(
    { url: `/Items/${id}`, method: "GET" },
    options,
  );
};

/**
 * @summary Обновить один айтем
 */
export const itemControllerUpdateItem = (
  id: string,
  updateItemDto: BodyType<UpdateItemDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/Items/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateItemDto,
    },
    options,
  );
};

/**
 * @summary Удалить айтем
 */
export const itemControllerRemoveItem = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/Items/${id}`, method: "DELETE" },
    options,
  );
};

export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-up`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signUpBodyDto,
    },
    options,
  );
};

export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-in`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signInBodyDto,
    },
    options,
  );
};

export const authControllerSignOut = (
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/auth/sign-out`, method: "POST" },
    options,
  );
};

export const authControllerGetSessionInfo = (
  options?: SecondParameter<typeof createInstance<GetSessionInfoDto>>,
) => {
  return createInstance<GetSessionInfoDto>(
    { url: `/auth/session`, method: "GET" },
    options,
  );
};

export const authControllerChangePassword = (
  changePasswordDto: BodyType<ChangePasswordDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/auth/change-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: changePasswordDto,
    },
    options,
  );
};

export type UserControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindAll>>
>;
export type UserControllerGetMeResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetMe>>
>;
export type UserControllerUpdateProfileResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>
>;
export type UserControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindOne>>
>;
export type UserControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdate>>
>;
export type UserControllerRemoveResult = NonNullable<
  Awaited<ReturnType<typeof userControllerRemove>>
>;
export type UserControllerUploadAvatarResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUploadAvatar>>
>;
export type AccountControllerGetAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerPatchAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>
>;
export type BlockListControllerGetListResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerGetList>>
>;
export type BlockListControllerAddBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerAddBlockItem>>
>;
export type BlockListControllerRemoveBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>
>;
export type PhotoControllerUploadPhotoResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerUploadPhoto>>
>;
export type PhotoControllerRemovePhotoResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerRemovePhoto>>
>;
export type ItemControllerCreateItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerCreateItem>>
>;
export type ItemControllerFindAllItemsResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerFindAllItems>>
>;
export type ItemControllerFindOneItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerFindOneItem>>
>;
export type ItemControllerUpdateItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerUpdateItem>>
>;
export type ItemControllerRemoveItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerRemoveItem>>
>;
export type AuthControllerSignUpResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignInResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;
export type AuthControllerGetSessionInfoResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AuthControllerChangePasswordResult = NonNullable<
  Awaited<ReturnType<typeof authControllerChangePassword>>
>;
