/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * My Backend by Ghost Raven
 * This API works with two entities: Users and Items. Each User can have multiple Items.
 * OpenAPI spec version: 1.0
 */
import { createInstance } from "../api-instance";
import type { BodyType } from "../api-instance";
export interface UpdateUserDto {
  [key: string]: unknown;
}

export interface AccountDto {
  id: number;
  ownerId: number;
  isBlockingEnabled: boolean;
}

export interface PatchAccountDto {
  isBlockingEnabled?: boolean;
}

export type BlockItemDtoType =
  (typeof BlockItemDtoType)[keyof typeof BlockItemDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockItemDtoType = {
  KeyWord: "KeyWord",
  Website: "Website",
} as const;

export interface BlockItemDto {
  id: number;
  blockListid: number;
  type: BlockItemDtoType;
  data: string;
  createdAt: string;
}

export interface BlockListDto {
  id: number;
  ownerId: number;
  items: BlockItemDto[];
}

export type AddBlockItemDtoType =
  (typeof AddBlockItemDtoType)[keyof typeof AddBlockItemDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddBlockItemDtoType = {
  KeyWord: "KeyWord",
  Website: "Website",
} as const;

export interface AddBlockItemDto {
  type: AddBlockItemDtoType;
  data: string;
}

export interface CreateItemDto {
  id: number;
  /** Заголовок статьи */
  title: string;
  /** Содержание статьи */
  content: string;
  /** Опубликована ли статья */
  published: boolean;
  /** ID автора статьи */
  authorId: number;
}

export interface UpdateItemDto {
  id?: number;
  /** Заголовок статьи */
  title?: string;
  /** Содержание статьи */
  content?: string;
  /** Опубликована ли статья */
  published?: boolean;
  /** ID автора статьи */
  authorId?: number;
}

export interface SignUpBodyDto {
  email: string;
  password: string;
}

export interface SignInBodyDto {
  email: string;
  password: string;
}

export interface GetSessionInfoDto {
  id: number;
  email: string;
  iat: number;
  exp: number;
}

export type BlockListControllerGetListParams = {
  q?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить всех пользователей
 */
export const userControllerFindAll = (
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/users`, method: "GET" }, options);
};

/**
 * @summary Получить одного пользователя
 */
export const userControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/users/${id}`, method: "GET" }, options);
};

/**
 * @summary Обновить пользователя
 */
export const userControllerUpdate = (
  id: string,
  updateUserDto: BodyType<UpdateUserDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/users/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserDto,
    },
    options,
  );
};

/**
 * @summary Удалить пользователя
 */
export const userControllerRemove = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/users/${id}`, method: "DELETE" },
    options,
  );
};

export const accountControllerGetAccount = (
  options?: SecondParameter<typeof createInstance<AccountDto>>,
) => {
  return createInstance<AccountDto>(
    { url: `/account`, method: "GET" },
    options,
  );
};

export const accountControllerPatchAccount = (
  patchAccountDto: BodyType<PatchAccountDto>,
  options?: SecondParameter<typeof createInstance<PatchAccountDto>>,
) => {
  return createInstance<PatchAccountDto>(
    {
      url: `/account`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchAccountDto,
    },
    options,
  );
};

export const blockListControllerGetList = (
  params?: BlockListControllerGetListParams,
  options?: SecondParameter<typeof createInstance<BlockListDto>>,
) => {
  return createInstance<BlockListDto>(
    { url: `/block-list`, method: "GET", params },
    options,
  );
};

export const blockListControllerAddBlockItem = (
  addBlockItemDto: BodyType<AddBlockItemDto>,
  options?: SecondParameter<typeof createInstance<BlockItemDto>>,
) => {
  return createInstance<BlockItemDto>(
    {
      url: `/block-list/item`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addBlockItemDto,
    },
    options,
  );
};

export const blockListControllerRemoveBlockItem = (
  id: number,
  options?: SecondParameter<typeof createInstance<BlockItemDto>>,
) => {
  return createInstance<BlockItemDto>(
    { url: `/block-list/item/${id}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary Создать все новые айтемы
 */
export const itemControllerCreateItem = (
  createItemDto: BodyType<CreateItemDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/Items`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createItemDto,
    },
    options,
  );
};

/**
 * @summary Получить все айтемы
 */
export const itemControllerFindAllItems = (
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/Items`, method: "GET" }, options);
};

/**
 * @summary Получить один айтем
 */
export const itemControllerFindOneItem = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>({ url: `/Items/${id}`, method: "GET" }, options);
};

/**
 * @summary Обновить один айтем
 */
export const itemControllerUpdateItem = (
  id: string,
  updateItemDto: BodyType<UpdateItemDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/Items/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateItemDto,
    },
    options,
  );
};

/**
 * @summary Удалить айтем
 */
export const itemControllerRemoveItem = (
  id: string,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/Items/${id}`, method: "DELETE" },
    options,
  );
};

export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-up`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signUpBodyDto,
    },
    options,
  );
};

export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-in`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signInBodyDto,
    },
    options,
  );
};

export const authControllerSignOut = (
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/auth/sign-out`, method: "POST" },
    options,
  );
};

export const authControllerGetSessionInfo = (
  options?: SecondParameter<typeof createInstance<GetSessionInfoDto>>,
) => {
  return createInstance<GetSessionInfoDto>(
    { url: `/auth/session`, method: "GET" },
    options,
  );
};

export type UserControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindAll>>
>;
export type UserControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindOne>>
>;
export type UserControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdate>>
>;
export type UserControllerRemoveResult = NonNullable<
  Awaited<ReturnType<typeof userControllerRemove>>
>;
export type AccountControllerGetAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerPatchAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>
>;
export type BlockListControllerGetListResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerGetList>>
>;
export type BlockListControllerAddBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerAddBlockItem>>
>;
export type BlockListControllerRemoveBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>
>;
export type ItemControllerCreateItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerCreateItem>>
>;
export type ItemControllerFindAllItemsResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerFindAllItems>>
>;
export type ItemControllerFindOneItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerFindOneItem>>
>;
export type ItemControllerUpdateItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerUpdateItem>>
>;
export type ItemControllerRemoveItemResult = NonNullable<
  Awaited<ReturnType<typeof itemControllerRemoveItem>>
>;
export type AuthControllerSignUpResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignInResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;
export type AuthControllerGetSessionInfoResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
